# version: "2"
# services:
#   web:
#     build: .
#     ports:
#       - "8083:8083"
#     links:
#       - mongo
#   mongo:
#     image: mongo
#     volumes:
#       - /data/mongodb/db:/data/db
#     ports:
#       - "27018:27017"

version: "2"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "8083:8083"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27018:27017"